#!/usr/bin/env python3
"""
Hermes Architect Audit -- Core PDF Generation Engine
=====================================================
Version: 5.2 (User-Corrected Design — Minimal Color Palette)
License: MIT

Description:
    Generates landscape A4 PDF audit reports for multi-agent LLM routing.
    Pure Python FPDF2 -- no external chart dependencies.
    Stable vertical-block card layout with zero truncation.
    Fully environment-agnostic: works on Linux, Mac, and Windows.

Author: Hgteo (VEGO64)
Repository: https://github.com/VEGO64/Hermes-Architect-Audit

Design Rules (v5.2 — User Corrected):
    BLACK = everything except 3 cases below:
    OPTION A: / OPTION B: = DARK BLUE bold
    [KEEP] = GREEN bold at START of first rationale line
    [SWITCH] = RED bold at START of first rationale line
    No emoji — use [KEEP] and [SWITCH] text only
"""

from fpdf import FPDF
from datetime import datetime
import os, sys, json

DATE = datetime.now().strftime("%Y-%m-%d")

# ─── Output Directory (absolute path for Hermes compatibility) ─────────────────
OUT = "/opt/data/cache/documents"
os.makedirs(OUT, exist_ok=True)

# ─── Font Setup (cross-platform fallback) ────────────────────────────────────
FONT_DIR = "/usr/share/fonts/truetype/dejavu"
if os.path.isdir(FONT_DIR):
    FPDF_FONT_DIR = FONT_DIR
else:
    FPDF_FONT_DIR = None

# ─── Layout Constants ────────────────────────────────────────────────────────
LM = 10   # Left margin mm
RM = 10   # Right margin mm
TM = 10   # Top margin
W = 277   # usable width (A4 landscape - margins)

# ─── Color Palette (v5.2 — Minimal: BLACK + 3 color cases) ─────────────────
BLACK  = (0,   0,   0)
WHITE  = (255, 255, 255)
LTGRAY = (220, 220, 220)
DKGRAY = (40,  40,  40)
RED    = (200, 50,  50)
GREEN  = (0,   130, 70)
BLUE   = (20,  60,  140)  # DARK BLUE for OPTION A/B labels

HDR_H = 30   # Page 1 header height
FTR_H = 10   # Footer height


class P(FPDF):
    def header(self):
        if self.page_no() == 1:
            self.set_fill_color(*BLACK)
            self.rect(0, 0, 297, HDR_H, 'F')
            self.set_y(7)
            self.set_font('S', 'B', 18)
            self.set_text_color(*WHITE)
            self.cell(0, 9, 'MODEL COST INTELLIGENCE', new_x='LMARGIN', new_y='NEXT', align='C')
            self.set_font('S', '', 9)
            self.set_text_color(200, 200, 200)
            self.cell(0, 5, f'Architect Audit v5  |  {DATE}  |  Full Analysis', new_x='LMARGIN', new_y='NEXT', align='C')
            self.set_y(HDR_H + 4)
        else:
            self.set_fill_color(*DKGRAY)
            self.rect(0, 0, 297, 13, 'F')
            self.set_y(3)
            self.set_font('S', 'B', 9)
            self.set_text_color(*WHITE)
            self.cell(0, 7, f'Model Cost Intelligence — Audit v5 — Page {self.page_no()}', new_x='LMARGIN', new_y='NEXT', align='C')
            self.set_y(17)

    def footer(self):
        self.set_y(-10)
        self.set_font('S', '', 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f'Generated by Hermes Agent | {DATE}', align='C')

    def section_title(self, txt):
        self.ln(3)
        self.set_font('S', 'B', 13)
        self.set_text_color(*BLACK)
        self.cell(0, 8, txt, new_x='LMARGIN', new_y='NEXT')
        self.set_draw_color(*BLACK)
        self.line(LM, self.get_y(), 287, self.get_y())
        self.ln(4)


def task_card(pdf, t):
    rat = t.get('rationale', '')
    est_lines = (len(rat) / 160) + 1
    est_rat_h = est_lines * 5.5
    total_h = 35 + est_rat_h + 10

    if pdf.get_y() + total_h > 190:
        pdf.add_page()

    y0 = pdf.get_y()
    IM = 14  # inner margin for content

    # TASK — BLACK
    pdf.set_x(IM)
    pdf.set_font('S', 'B', 12)
    pdf.set_text_color(*BLACK)
    pdf.cell(0, 7, f"TASK: {t.get('name','').upper()}", new_x='LMARGIN', new_y='NEXT')

    # CURRENT — BLACK
    pdf.set_x(IM)
    pdf.set_font('S', '', 9)
    pdf.set_text_color(*BLACK)
    pdf.cell(0, 5, f"CURRENT: {t.get('current','')} | In ${t.get('cur_in','')}/1M | Out ${t.get('cur_out','')}/1M", new_x='LMARGIN', new_y='NEXT')
    pdf.ln(2)

    # OPTIONS — label in DARK BLUE bold, rest in BLACK
    for lbl, name, in_c, out_c, ctx in [
        ("OPTION A (Efficiency/Cost Leader): ", t.get('opt_a_name'), t.get('a_in'), t.get('a_out'), t.get('a_ctx')),
        ("OPTION B (Performance/Quality Leader): ", t.get('opt_b_name'), t.get('b_in'), t.get('b_out'), t.get('b_ctx'))
    ]:
        pdf.set_x(IM)
        pdf.set_font('S', 'B', 9)
        pdf.set_text_color(*BLUE)
        lw = pdf.get_string_width(lbl)
        pdf.cell(lw, 5.5, lbl)
        pdf.set_font('S', '', 9)
        pdf.set_text_color(*BLACK)
        pdf.multi_cell(W - lw - 4, 5.5, f"{name} | In ${in_c}/1M | Out ${out_c}/1M | Context: {ctx}")
        pdf.ln(1)

    # FINAL RECOMMENDATION header — BLACK bold
    pdf.set_x(IM)
    pdf.set_font('S', 'B', 9)
    pdf.set_text_color(*BLACK)
    pdf.cell(0, 5.5, "FINAL RECOMMENDATION:", new_x='LMARGIN', new_y='NEXT')

    # Badge at BEGINNING of first rationale line
    rec_label = t.get('rec_label', '')
    badge_text = ''
    badge_color = BLACK
    if 'SWITCH' in rec_label.upper():
        badge_text = '[SWITCH] '
        badge_color = RED
    elif 'KEEP' in rec_label.upper():
        badge_text = '[KEEP] '
        badge_color = GREEN

    pdf.set_x(IM + 4)
    if badge_text:
        pdf.set_font('S', 'B', 9)
        pdf.set_text_color(*badge_color)
        pdf.cell(pdf.get_string_width(badge_text), 5.5, badge_text)

    # Rationale text — word by word with badge inline on first line
    pdf.set_font('S', '', 9)
    pdf.set_text_color(*BLACK)
    rat_words = rat.split(' ')
    line_buf = ''
    first_line_done = False
    badge_w = pdf.get_string_width(badge_text) if badge_text else 0

    for w in rat_words:
        test = (line_buf + ' ' + w).strip()
        avail_w = W - (IM + 4 + (badge_w if not first_line_done else 0)) - 4
        if pdf.get_string_width(test) > avail_w:
            if line_buf:
                pdf.cell(0, 5.5, line_buf, new_x='LMARGIN', new_y='NEXT')
                first_line_done = True
            line_buf = w
        else:
            line_buf = test
    if line_buf:
        pdf.cell(0, 5.5, line_buf, new_x='LMARGIN', new_y='NEXT')
    pdf.ln(4)

    # Card border
    y1 = pdf.get_y()
    pdf.set_draw_color(*LTGRAY)
    pdf.rect(LM, y0, W, y1 - y0)
    pdf.set_y(y1 + 5)


def build(d):
    pdf = P()
    if FPDF_FONT_DIR:
        pdf.add_font('S', '',  f'{FPDF_FONT_DIR}/DejaVuSans.ttf')
        pdf.add_font('S', 'B', f'{FPDF_FONT_DIR}/DejaVuSans-Bold.ttf')
    pdf.set_margins(LM, TM, RM)
    pdf.set_auto_page_break(True, 15)

    # Page 1
    pdf.add_page()
    pdf.section_title('User Behavior Profile')
    pdf.set_font('S','',10)
    pdf.set_text_color(*BLACK)
    pdf.multi_cell(0, 5.5, d.get('profile',''))
    pdf.section_title('Executive Summary & Strategic Roadmap')
    pdf.multi_cell(0, 5.5, "Unified model routing strategy based on 11 task modules.")

    for t in d.get('tasks', []):
        task_card(pdf, t)

    out_path = f"{OUT}/Model_Cost_Intelligence_{DATE}_v5.pdf"
    pdf.output(out_path)
    return out_path


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 generate_audit_pdf.py '<json_payload>'")
        sys.exit(1)
    try:
        data = json.loads(sys.argv[1])
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        sys.exit(1)
    result = build(data)
    print(f"PDF_PATH:{result}")